name: Killstreak
version: @version@-@apiversion@
description: Deathmatch Rankup Plugin
author: DartPower
website: https://github.com/dptmc/Killstreak
main: io.dpteam.Killstreak.Main
commands:
  ks:
    desciprtion: Open killstreak menu