name: Killstreak
version: @version@-@apiversion@
description: Deathmatch Rankup Plugin
author: DartPower
website: https://github.com/dptmc/Killstreak
main: io.dpteam.Killstreaks.Main
api-version: 1.13
commands:
  ks:
    desciprtion: Open killstreak menu